### ISSUE TITLE
TypeError: browser.addEvent is not a function

### ISSUE THREAD

**Issue by Alterock13** [ivsgroup/mdns-spawn#8]
Hi,

I've tried using this module today, following the instructions : 
```
const MDNS_Spawn = require('mdns-spawn');
var browser = new MDNS_Spawn();
```
This worked fine but then when I entered : 
```
browser.addEvent('serviceUp', function(service){console.log(service);});
```

I got the error : 
`TypeError: browser.addEvent is not a function`

Could you please tell me if it's an issue on my side or not ?
Thanks.

**Comment by 131** [comment]
addEvent is a legacy syntax i've missed to update from the README (until now).
Use `browser.on(`  to register to mdns-spawn events.
